[mgr]
prepend_keymap = [
{ on = [ "<C-d>" ], run = '''
shell 'dragon -x -i -T "$1"' --confirm
''' },
{on = "!", for  = "unix", run  = 'shell "$SHELL" --block', desc = "Open $SHELL here"},
{on = "t", run  = "plugin smart-tab", desc = "Create a tab and enter the hovered directory"},
{on = "y", run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]},
{on = "T", run  = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane"},
{on   = "l", run  = "plugin smart-enter", desc = "Enter the child directory, or open the file"},
{on   = "p", run  = "plugin smart-paste", desc = "Paste into the hovered directory or CWD"},
{on  = "M", run = "plugin mount"},
{on   = [ "c", "m" ], run  = "plugin chmod", desc = "Chmod on selected files"},
{on = "<A-y>",run = ["plugin copy-file-contents"], desc = "Copy contents of file"},

]
[input]
prepend_keymap = [
{on   = "<Esc>", run  = "close", desc = "Cancel input"}
]


